[package]
name = "fks-dict"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
num-primes = "0.3.0"
rstest = "0.16.0"
rs_merkle="1.2.0"